name: slidable_tab_bar
description: A smoothly slidable tab bar view for Flutter.
version: 0.0.1
homepage: https://github.com/nivisi/slidable_tab_bar
repository: https://github.com/nivisi/slidable_tab_bar
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
